<?php 
  $this->headTitle('Kontakt');
  $this->headLink()->appendStylesheet($this->baseUrl() . '/styles/kontakt.css');
?>
<div class="row-2">
  <div class="container">
    <div class="column-1">
      <?php echo $this->partial('sidemenu.phtml'); ?>
    </div>
    <div class="column-2">
      <div class="indent">
        <div class="container unline">
          <div class="title"><strong>Godziny otwarcia</strong></div>
          <div class="text1">
            <ul>
              <li>poniedziałek, wtorek, środa i piątek : 10 - 18</li>
              <li>czwartek : 10 - 19.30</li> 
              <li>sobota : 10 - 14</li>
            </ul>
          </div>
        </div>
        <div class="container unline">
          <div class="title"><strong>Adres</strong></div>
          <div class="text1">
            <ul>
              <li>Sklep Margot</li>
              <li>Pasaż "Centrum Targowa"</li>
              <li>ul. Targowa 33a lok. 15/13</li> 
              <li>03-728 Warszawa</li>
              <li>tel. 501 575 829</li>
              <li>poczta@suknie-margot.pl<li>
            </ul>
          </div>
        </div>
        <div class="container last">
          <div class="title"><strong>Mapa</strong></div>
          <div class="text1">
            <div class="map-container">
            <iframe width="300" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=pl&amp;geocode=&amp;q=Targowa+33+Warszawa&amp;sll=52.133488,18.94043&amp;sspn=19.881954,57.084961&amp;ie=UTF8&amp;hq=&amp;hnear=Targowa+33,+Warszawa,+Mazowieckie,+Polska&amp;ll=52.250059,21.041007&amp;spn=0.007882,0.012875&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=pl&amp;geocode=&amp;q=Targowa+33+Warszawa&amp;sll=52.133488,18.94043&amp;sspn=19.881954,57.084961&amp;ie=UTF8&amp;hq=&amp;hnear=Targowa+33,+Warszawa,+Mazowieckie,+Polska&amp;ll=52.250059,21.041007&amp;spn=0.007882,0.012875&amp;z=15&amp;iwloc=A" style="text-align:left">Wyświetl większą mapę</a></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>