<?php 
  $this->headTitle('O nas');
  $this->headLink()->appendStylesheet($this->baseUrl() . '/styles/onas.css'); 
?>
<div class="row-2">
  <div class="container">
    <div class="column-1">
      <?php echo $this->partial('sidemenu.phtml'); ?>
    </div>
    <div class="column-2">
      <div class="indent">
        <div class="container unline"><img src="<?php echo $this->baseUrl() ?>/images/onas1.jpg"
          class="imgindent2" alt="" />
          <div class="text1">
          <p>Sklep Margot powstał jesienią 2009 roku i od samego początku oferuje szeroki asortyment eleganckich sukienek dla Pań. Kolekcje dostępne w sklepie mają oryginalne wzornictwo połączone z doskonałym stylem i szczyptą ekstrawagancji, zgodną z aktualnymi trendami.</p>
          <p>Ciekawy krój i wysoka jakość tkanin połączona z profesjonalnym wykonaniem czyni nasze suknie ładnymi w wyglądzie i wygodnymi w noszeniu.</p>
          </div>
        </div>
        <div class="container unline"><img src="<?php echo $this->baseUrl() ?>/images/onas2.jpg"
          class="imgindent2" alt="" />
          <div class="text1">
          <p>Specjalnością firmy są przede wszystkim suknie wizytowe i koktajlowe, a także suknie na specjalne okazje i przyjęcia, takie jak bale sylwestrowe, wieczory karnawałowe, studniówki i wesela.</p>
          <p>Proponujemy również wyszukane dodatki w postaci żakietów, bolerek, torebek, szali i upięć kwiatowych.</p>
          </div>
        </div>
        <div class="container unline"><img src="<?php echo $this->baseUrl() ?>/images/onas3.jpg"
          class="imgindent2" alt="" />
          <div class="text1">
          <p>Oferujemy także sukienki biznesowe i konferencyjne, łączące elegancję z prostotą i komfortem użytkowania.</p>
          <p>Stale w sprzedaży mamy duży wybór sukni. W salonie dostępnych jest stale ponad 100 modeli w rozmiarach od 34 do 50. Jesteśmy też w stanie zrealizować w krótkim terminie zamówienia niekonwencjonalne.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
