<div class="box2">
  <div class="left-border">
    <div class="right-border">
      <div class="left-top">
        <div class="right-top">
          <div class="bot-border">
            <div class="indent">
              <div class="title">Galeria :</div>
              <ul class="list">
                <li><?php $this->printLink('/galeria', 'Wieczorowe') ?></li>
                <li><?php $this->printLink('/galeria', 'Na dzień') ?></li>
                <li><?php $this->printLink('/galeria', 'Dodatki') ?></li>
                <li><?php $this->printLink('/galeria', 'Nowości') ?></li>
                <li><?php $this->printLink('/galeria', 'Promocje') ?></li>
                <li><?php $this->printLink('/galeria', 'Wszystkie') ?></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
