<?php

$this->headTitle('Galeria');
$this->headScript()->appendFile($this->baseUrl() . '/javascript/filters.js');
$this->headScript()->appendFile($this->baseUrl() . '/javascript/list.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/gallery.css');
?>
<script>
var params = <?php echo $this->params  ?>;
</script>
<div class="row-2">
  <div class="container">
    <div class="column-1">
      <div class="box2">
        <div class="left-border">
          <div class="right-border">
            <div class="left-top">
              <div class="right-top">
                <div class="bot-border">
                  <div id="list-panel" class="indent">

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="column-2">
      <div id="list-container"></div>
    </div>
  </div>
</div>
